baseurl: ''
url: https://www.oneweektickets.com
title: OneWeek Tickets
tagline: Price Discovery For the Primary Market
description: >-
  An innovative ticketing platform that helps venues, artists, promoters, and fans 
  all have a better experience by enabling auction pricing in the primary market.
author: OneWeek
logo: /favicon.ico
lang: en_US
favicon: /favicon.ico
og_image: /assets/images/bg-hero.jpg
mailchimp-list: https://oneweektickets.us1.list-manage.com/subscribe/post?u=f0d949cdf0a6a387f7b55a173&amp;id=4f123ead61
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
gems:
  - jekyll-paginate-v2
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
include:
  - account-settings
  - manage
  - _pages
exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
collections:
  events:
    output: true
defaults:
  - scope:
      path: ''
    values:
      layout: page
      author: oneweek
  - scope:
      path: ''
      type: posts
    values:
      layout: blog-single
      permalink: '/:title'
      is_post: true
  - scope:
      path: _pages
    values:
      layout: page
      permalink: '/:basename/'
  - scope:
      path: _events
    values:
      layout: event-details
      permalink: '/e/:path/'
      sitemap: false
  - scope:
      path: account-settings
    values:
      layout: account-settings
      permalink: '/:path/:basename/'
      sitemap: false
  - scope:
      path: manage
    values:
      layout: page
      permalink: '/:path/:basename/'
      sitemap: false
  - scope:
      path: organizations
    values:
      layout: page
      permalink: '/:path/:basename/'
      sitemap: false
  - scope:
      path: "assets/*"
    values:
      sitemap: false
  - scope:
      path: "emails/*"
    values:
      sitemap: false
cloudinary:
  cloud_name: judsonlmoore-com
  only_prod: true
  verbose: false
  presets:
    default:
      gravity: auto
      crop: fill
      focus: auto
      min_width: 256
      max_width: 1024
      figure: never
      attributes:
        class: img-fluid mb-2 mt-3 w-100
        loading: lazy
    post-image: 
      gravity: auto
      crop: fill
      focus: auto
      steps: 3
      min_width: 290
      min_height: 130
      max_width: 930
      max_height: 418
      figure: never
      attributes:
        class: img-fluid rounded mb-2 mt-3 w-100
        loading: lazy
    postbox: 
      gravity: auto
      crop: fill
      focus: auto
      steps: 2
      min_width: 330
      min_height: 220
      max_width: 350
      max_height: 240
      figure: never
      attributes:
        class: img-fluid rounded
        loading: lazy
    author:
      gravity: auto
      crop: fill
      focus: auto
      steps: 2
      min_width: 70
      min_height: 70
      max_width: 70
      max_height: 70
      figure: never
      attributes:
        class: img-fluid avatar-xl rounded-circle me-3
        loading: lazy
    logo:
      gravity: auto
      crop: fill
      focus: auto
      steps: 2
      min_width: 150
      min_height: 50
      max_width: 200
      max_height: 150
      figure: never
      attributes:
        class: img-fluid h-100 w-100
        loading: lazy
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
  endings:
    - html
    - head
    - body
    - li
    - dt
    - dd
    - rt
    - rp
    - optgroup
    - option
    - colgroup
    - caption
    - thead
    - tbody
    - tfoot
    - tr
    - td
    - th
  profile: false
  blanklines: false
  ignore:
    envs: []
pagination:
  enabled: false
  per_page: 9
  permalink: '/page-:num/'
  title: ':title'
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: false
  categories:
    layouts:
      - autopage.html
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    slugify:
      mode: default
      case: true
  tags:
    layouts:
      - autopage.html
    title: 'Posts tagged with :tag'
    permalink: '/tag/:tag'
    slugify:
      mode: default
      case: true
  collections:
    layouts:
      - autopage.html
    title: 'Posts in collection :coll'
    permalink: '/collection/:coll'
    slugify:
      mode: default
      case: true