name: Jekyll Deploy

on:
  push:
    branches:
      - production

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: Upload to GCP Bucket
      uses: weslenng/gcp-storage-sync@master
      with:
        args: -d
        args: -z css,js,html
      env:
        GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
        GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET }}
        SOURCE_DIR: "_site"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: oneweek-tickets
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
        export_default_credentials: true
    - name: Invalidate cache ASYNC
      run: gcloud compute url-maps invalidate-cdn-cache oneweektickets-lb --path "/*" --async