name: Jekyll Deploy

on:
  push:
    branches:
      - staging

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - restore_cache:
      key: jekyll-{{ .Branch }}-{{ checksum "Gemfile" }}
    - run:
      name: Update gems
      command: gem update --system
    - run:
      name: Install dependencies
      command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - save_cache:
      key: jekyll-{{ .Branch }}-{{ checksum "Gemfile" }}
      paths:
        - "vendor/bundle"
    - run:
      name: Build site
      command: bundle exec jekyll build --config _config.yml,_config-staging.yml 2>&1
    - run:
      name: Remove .html suffixes
      command: find _site -name "*.html" -not -name "index.html" -exec rename -v 's/\.html$//' {} \;
    - name: Upload to GCP Bucket
      uses: weslenng/gcp-storage-sync@master
      with:
        args: -d
      env:
        GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
        GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET_STAGING }}
        SOURCE_DIR: "_site"
 




