name: Jekyll Deploy

on:
  push:
    branches:
      - staging

jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Ruby gem cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build Jekyll site
      run:  bundle exec jekyll build --config _config.yml,_config-staging.yml
    - name: Upload to GCP Bucket
      uses: weslenng/gcp-storage-sync@master
      with:
        args: -d
      env:
        GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
        GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET_STAGING }}
        SOURCE_DIR: "_site"
 




